name: Publish to NPM

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0
  workflow_dispatch:  # Allows manual triggering from GitHub UI
    inputs:
      version:
        description: 'Version to publish (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./dashboard
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build package
        run: npm run build
      
      - name: Update package.json for publishing
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            # Manual trigger - use the input version
            npm pkg set version="${{ github.event.inputs.version }}"
          else
            # Tag trigger - extract version from tag
            TAG_VERSION=${GITHUB_REF#refs/tags/v}
            npm pkg set version="$TAG_VERSION"
          fi
      
      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event_name == 'workflow_dispatch' && format('v{0}', github.event.inputs.version) || github.ref }}
          release_name: ${{ github.event_name == 'workflow_dispatch' && format('Release v{0}', github.event.inputs.version) || format('Release {0}', github.ref) }}
          body: |
            ## What's Changed
            
            Published @nearai/analytics-dashboard@${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version || github.ref_name }} to NPM.
            
            ### Installation
            ```bash
            npm install @nearai/analytics-dashboard
            ```
            
            ### Usage
            See [Web Component Usage Guide](./dashboard/WEB_COMPONENT_USAGE.md) for detailed documentation.
          draft: false
          prerelease: false
